stages:
  - build
  - deploy

variables:
  # Define the SSH_PRIVATE_KEY variable as a CI/CD secret variable in GitLab.
  # The value should be your private SSH key.
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"

build:
  stage: build
  image: node:13  # Use an official Node.js image with npm pre-installed
  script:
    - npm install
    - npm install -g @angular/cli@7.0.4  # Install the Angular CLI globally if needed
    - ng build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y sshpass

    # Create the ~/.ssh directory if it doesn't exist
    - mkdir -p ~/.ssh

    # Create an SSH key file from the provided private key variable
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    # Enable SSH agent and add the SSH key
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa

    # Use the SSH key for authentication and adjust the command accordingly.
    # Make sure your SSH public key is added to the authorized_keys file on the server.
    - scp -o StrictHostKeyChecking=no -r dist/* jenkins@20.64.155.18:/var/www/html/1800-limo