stages:
  - build
  - deploy
variables:
  # Define the SSH_PRIVATE_KEY variable as a CI/CD secret variable in GitLab.
  # The value should be your private SSH key.
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"
build:
  stage: build
  image: node:13  # Use an official Node.js image with npm pre-installed
  script:
    - npm install
    - npm install -g @angular/cli@7.0.4  # Install the Angular CLI globally if needed
    - ng build
  artifacts:
    paths:
      - dist/
deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y sshpass
    # Use the SSH private key for authentication, and adjust the command accordingly.
    # Make sure your SSH private key is set as a CI/CD secret variable named SSH_PRIVATE_KEY.
    - echo "$SSH_PRIVATE_KEY" > id_rsa  # Save the SSH private key to a temporary file
    - chmod 600 id_rsa  # Set appropriate permissions for the SSH private key
    # Use the -P option to specify the custom SSH port (2224 in this example).
    - scp -i id_rsa -o StrictHostKeyChecking=no -r dist/* jenkins@20.64.155.18:/var/www/html/1800-limo